openapi: 3.0.0
info:
  title: Nexus Comments API
  description: APIs for managing comments on tasks in the Nexus multi-tenant platform
  version: '1.0'

paths:
  /workspaces/{workspaceId}/tasks/{taskId}/comments:
    post:
      summary: Create a new comment
      description: Creates a new comment on a task
      tags:
        - Comments
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: Comment text content
                  maxLength: 5000
                parent_comment_id:
                  type: string
                  description: ID of parent comment if this is a reply
                mentions:
                  type: array
                  description: User IDs mentioned in the comment
                  items:
                    type: string
      responses:
        '201':
          description: Comment created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment_id:
                    type: string
                  content:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  created_by:
                    type: object
                    properties:
                      user_id:
                        type: string
                      name:
                        type: string
        '400':
          description: Invalid request parameters
        '403':
          description: Not authorized to comment on this task
        '404':
          description: Workspace or task not found
        '500':
          description: Server error
    
    get:
      summary: List comments
      description: Returns a list of comments for a task
      tags:
        - Comments
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: cursor
          in: query
          required: false
          schema:
            type: string
            description: Pagination cursor
      responses:
        '200':
          description: List of comments
          content:
            application/json:
              schema:
                type: object
                properties:
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        comment_id:
                          type: string
                        content:
                          type: string
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                        created_by:
                          type: object
                          properties:
                            user_id:
                              type: string
                            name:
                              type: string
                        parent_comment_id:
                          type: string
                        reply_count:
                          type: integer
                  cursor:
                    type: string
                    description: Pagination cursor for the next page
        '403':
          description: Not authorized to view comments on this task
        '404':
          description: Workspace or task not found
        '500':
          description: Server error

  /workspaces/{workspaceId}/tasks/{taskId}/comments/{commentId}:
    get:
      summary: Get comment details
      description: Returns details for a specific comment
      tags:
        - Comments
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
        - name: commentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Comment details
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment_id:
                    type: string
                  content:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  created_by:
                    type: object
                    properties:
                      user_id:
                        type: string
                      name:
                        type: string
                  parent_comment_id:
                    type: string
        '403':
          description: Not authorized to view this comment
        '404':
          description: Comment not found
        '500':
          description: Server error
    
    put:
      summary: Update comment
      description: Updates the content of a comment
      tags:
        - Comments
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
        - name: commentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: Updated comment text
                  maxLength: 5000
                mentions:
                  type: array
                  description: Updated user IDs mentioned in the comment
                  items:
                    type: string
      responses:
        '200':
          description: Comment updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment_id:
                    type: string
                  content:
                    type: string
                  updated_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid request parameters
        '403':
          description: Not authorized to update this comment
        '404':
          description: Comment not found
        '500':
          description: Server error
    
    delete:
      summary: Delete comment
      description: Deletes a comment
      tags:
        - Comments
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
        - name: commentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Comment deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  comment_id:
                    type: string
        '403':
          description: Not authorized to delete this comment
        '404':
          description: Comment not found
        '500':
          description: Server error

  /workspaces/{workspaceId}/tasks/{taskId}/comments/{commentId}/replies:
    get:
      summary: Get comment replies
      description: Returns replies to a specific comment
      tags:
        - Comments
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
        - name: commentId
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: cursor
          in: query
          required: false
          schema:
            type: string
            description: Pagination cursor
      responses:
        '200':
          description: List of replies to the comment
          content:
            application/json:
              schema:
                type: object
                properties:
                  replies:
                    type: array
                    items:
                      type: object
                      properties:
                        comment_id:
                          type: string
                        content:
                          type: string
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                        created_by:
                          type: object
                          properties:
                            user_id:
                              type: string
                            name:
                              type: string
                  cursor:
                    type: string
                    description: Pagination cursor for the next page
        '403':
          description: Not authorized to view replies to this comment
        '404':
          description: Comment not found
        '500':
          description: Server error

components:
  securitySchemes:
    cognitoAuth:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools

security:
  - cognitoAuth: [] 